server:
  port: 8001


spring:
  application:
    name: mall-auth
  redis:
    host: 114.116.105.15
    jedis:
      pool:
        max-active: 8
  cloud:
    nacos:
      discovery:
        server-addr: 114.116.105.15:8848

## http://localhost:8080/doc.html knif4J 地址
mall:
  swagger:
    enable: true
    basePackage: com.salute.mall.auth.service.controller
    title: mall-auth
    description: salute-mall认证中心接口文档
    contact: melo-lh
    version: 1.0

  redisson:
    address: 114.116.105.15:6379